site_name: Tasca4-Material
docs_dir: "md"
site_dir: "docs"
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
theme:
  name: 'material'
  font:
    text: 'Roboto, sans-serif'
    code: 'Courier New, monospace'
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Modo oscuro
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Modo claro
features:
  - navigation.sections
plugins:
  - search
  - page-to-pdf:
      # Opciones del plugin
      disable: false
      disableOnServe: false
      scale: 1.0
      format: A4
      margin:
        top: "20px"
        right: "20px"
        bottom: "20px"
        left: "20px"


